[tool.black]
target-version = ['py39', 'py310', 'py311']
preview = true
[tool.isort]
profile = "black"
[tool.autopep8]
# Use same max line length as the default in Black - 88
max_line_length = 88
# Ignore errors that conflict with Black
# E201 - whitespace after ‘(‘
# E202 - whitespace before ‘)’
# E203 - whitespace before ‘:’
# Ignore E731 - do not assign a lambda expression, use a def
ignore = ['E201', 'E202', 'E203', 'E731']
recursive = true
aggressive = 1
